// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyatcbxhyyuabmoziliq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5YXRjYnhoeXl1YWJtb3ppbGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTUzMDAsImV4cCI6MjA3MjE5MTMwMH0.0mKuBsBwm-D0XFvTEZ3qb0GZ3Z8OYZbT2grRWyAxIWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});